<?xml version="1.0"?>
<package format="3">
  <name>docking_description</name>
  <version>0.1.0</version>
  <description>Spacecraft and docking interface descriptions.</description>
  <maintainer email="maintainer@example.com">Secure Docking Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>